version: "3"
services:
  react-app:
    image: react-app-dev
    environment:
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
    stdin_open: true
    ports: 
      - "80:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - API_TOKEN=${API_TOKEN}
      - API_ENDPOINT=${API_ENDPOINT}
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  mern-app:
    driver: bridge